// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalRevealController from "./modal_reveal_controller"
application.register("modal_reveal", ModalRevealController)

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import MapController from "./map_controller"
application.register("map", MapController)
